"""Improve chapter titles using OpenAI when an API key is available.

Each synthesised chapter title starts life as the first sentence of the
transcript paragraph at that boundary — raw subtitle text, not a summary.
This module replaces those raw titles with concise, descriptive headings
generated by GPT-4o.
"""

from __future__ import annotations

from video_star.models.pipeline_result import Chapter


def refine_chapter_titles(chapters: list[Chapter], api_key: str) -> list[Chapter]:
    """Return a new list of chapters with OpenAI-generated titles.

    Sends all chapter texts to GPT-4o in a single request to minimise
    latency and API cost.  Falls back to the original titles if the call
    fails for any reason.
    """
    if not chapters or not api_key:
        return chapters

    try:
        return _refine_with_openai(chapters, api_key)
    except Exception:
        return chapters


# ---------------------------------------------------------------------------
# Internal
# ---------------------------------------------------------------------------

def _refine_with_openai(chapters: list[Chapter], api_key: str) -> list[Chapter]:
    from openai import OpenAI

    client = OpenAI(api_key=api_key)

    # Build a numbered list so the model can return titles in order.
    numbered = "\n".join(
        f"{i + 1}. {c.title}" for i, c in enumerate(chapters)
    )

    prompt = (
        "You are helping create YouTube chapter titles for a video.\n\n"
        "Below is a numbered list of draft chapter titles. Each draft was "
        "automatically extracted from the transcript and may read like raw "
        "subtitle text rather than a polished heading.\n\n"
        "Rewrite each title as a short, descriptive YouTube chapter heading "
        "(3–6 words, title case, no punctuation at the end). "
        "Preserve the exact numbering. Return ONLY the numbered list — no "
        "extra commentary.\n\n"
        f"{numbered}"
    )

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=300,
        temperature=0.4,
    )

    raw_output = (response.choices[0].message.content or "").strip()
    new_titles = _parse_numbered_list(raw_output, len(chapters))

    return [
        Chapter(start=c.start, title=new_titles[i] or c.title)
        for i, c in enumerate(chapters)
    ]


def _parse_numbered_list(text: str, expected: int) -> list[str]:
    """Extract titles from a numbered list response, falling back per-item."""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    titles: list[str] = []
    for line in lines:
        # Match "1. Title text" or "1) Title text"
        if line and line[0].isdigit():
            remainder = line.lstrip("0123456789").lstrip(". )")
            if remainder:
                titles.append(remainder.strip())
    # If parsing produced the wrong count, pad/truncate conservatively.
    while len(titles) < expected:
        titles.append("")  # will be replaced by original below
    return titles[:expected]
